### ISSUE TITLE
WARNING - nasty little patch

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-client#29]
this commit ce09df1f81244f9ab123208de673552d3dce25a4
probably shouldn't have been a patch level change @dominictarr 

It fundamentally changes the expectations of ssb-client options: 
- removes default scuttleverse cap (how are people now supposed to know this @cryptix ?)
  - for the record :  `1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=`
- demands a new config option present: `config.caps.shs`

**Comment by mixmix** [comment]
looks like this breaks patchcore. It was this innocuous looking change in ssb-client : 

```js
   var shs = Shs({
     keys: toSodiumKeys(keys),
-    appKey: opts.appKey || appKey,
+    appKey: appKey,

```

I'll make a patch to patchcore later today.

I think `ssb-config` might be providing the default cap? Appreciate that you're workingto straighten all this out. Sorry if I sound grumpt it's me trying to work on a deadline but getting caught with yak 
Is there anything that needs talking about here.

**Comment by mmckegg** [comment]
@mixmix thanks for getting to the bottom of and posting this!

I just made a change to patchcore to fix this and published as 1.23.3

**Comment by mmckegg** [comment]
Eh, something is still broken when I burn them all 😢

**Comment by mmckegg** [comment]
Problem seems to be related to `createUserFeed`.

```
  pull(
    sbot.createUserFeed({id: "@FbGoHeEcePDG3Evemrc+hm+S77cXKf8BRQgkYinJggg=.ed25519"}),
    pull.drain((msg) => {
      console.log(msg)
    }, (msg) => {
      console.log("END")
    })
  )
```

For me, only the first item is logged out and then it hangs. `"END"` is never logged.

Any ideas @dominictarr ?? Have you changed anything recently in a scuttlebot dep that could affect this?

**Comment by cryptix** [comment]
for the record, i tried to reach out to you guys some days ago after coming across this myself.. see ssbc/patchcore#55.

I also tried to notify on ssb but I think my updates always get drowned by the diff in our timezones...

**Comment by mixmix** [comment]
yeah not blaming you - there's gonna be pains with bringing the system into some coherence. Thanks for your work @cryptix

**Comment by evbogue** [comment]
I saw @cryptix's message on the network, and made sure to test the patch. It turned out that this patch was an improvement for me, so I'm grateful that Henry took the time to put it together and finally make `ssb-client` network agnostic. I wouldn't call his patch 'nasty', as it is an improvement.

However, I see that it broke something in Patchcore. I want to help you guys fix that!

Are you getting any errors when using this new version of `ssb-client`? If you can post the errors you're getting, we can help track down where Patchcore is breaking with the new patch.

**Comment by evbogue** [comment]
In fact, I was able to unfork `ssb-client` in Decent because of @cryptix's patch! Here's the commit from 6 days ago: https://github.com/evbogue/decent/commit/2da29c06fad399d4830b605784bcfda7af3d89a2

**Comment by mmckegg** [comment]
yeah, this was more of an issue with patchcore than anything else

It can be really difficult to know whether it is safe to push something as “patch”, “minor” or “major”.  

I think that’s what mix meant by “patch” (not patch as a code change). It was a good code change :) but was an unfortunate increment.

**Comment by mmckegg** [comment]
Okay, looks like all of my recent issues in Patchwork have come down to the ssb-client module getting patch updates when they should have been breaking!

- ssb-client@4.5.4 broke patchcore because it no longer had a default caps key (mostly patchcore's fault here because it shouldn't have assumed)
- ssb-client@4.5.5 broke a lot of random things in patchwork because it forced an upgrade of muxrpc to version 7, which apparently still has some issues to work through.

All in all, a pretty sad week for semver and npm 😢 

I have since pinned ssb-client@4.5.2 in patchwork, and now all of my issues have gone away (for now).

**By the way as a side note, I can highly recommend the [whathappended](https://www.npmjs.com/package/whathappened) module for getting to the bottom of this sort of broken dep problem.**

**Comment by evbogue** [comment]
I haven't tested muxrpc@7, so it's good to know that I'm going to be auto-upgraded to that version. I'll lock in at a previous version. Thanks for figuring this out @mmckegg!

**Comment by dominictarr** [comment]
I thought this was a patch because latest ssb-config supplies the caps, but it turns out installing this doesn't necessarily install ssb-config. This should be fixed in 4.5.6 though, can anyone confirm?

**Comment by mixmix** [comment]
have been talking with @cryptix on the buttz - feels like an emerging need for something ... like a call about core stuff. I'm keen to lean into supporting the development and documentation of this so that everyone can have a more awesome time.

I wonder if it's time to start having the master / latest commit be different than known stable ones for some certain modules. Or maybe we just barrel into changes and sort them out together but communicate kindly and clearly about what's on fire :P

**Comment by dominictarr** [comment]
on that note, now would also be a good time to mention that it's a lot of responsibility to be the only one who's maintaining this stuff. Sometimes I make pull requests back to it (so that other people can see it, and comment) and nothing. [recent example](https://github.com/ssbc/ssb-markdown/pull/21)

**Comment by dominictarr** [comment]
I'd be very happy to discuss ways to share that role a bit more and or make it easier.

**Comment by evbogue** [comment]
Let's have a call. I'm available until Tuesday, and presenting on Wednesday.

**Comment by evbogue** [comment]
That being said, I don't think this patch was anything other than a success. Thanks @cryptix for making it happen. And thanks to @dominictarr for merging it.

I understand that a few things broke downstream, but things break! #madscience.

**Comment by mixmix** [comment]
Keen to talk about how to get the back end better suppor, including taking
on some responsibility and review.
Can we do a Berlin Chicago NZ time or is that timing going to be
impossible.

Ev your words of support and encouragement are really sweet. Thank you

**Comment by evbogue** [comment]
@mixmix 
10pm Hamburg
3pm Chicago
10am Wellington 
is probably doable, right?

**Comment by mixmix** [comment]
I can do that, or can move it an hour earlier.
@cryptix @dominictarr does the proposed time work? 

Can you do sometime in the second half of the next week?
thanks for doing the timezone maths @evbogue  (man I would love a helper in scuttlebutt for this!)

**Comment by evbogue** [comment]
I know I'm not available Tuesday* 2/20 (I get off work at 3:30pm), Wednesday 2/21 (presenting at Node.js Chicago) and Thursday 2/22 (I get off work at 3:30pm) next week. I am available Monday, Friday and Saturday at these times.

* keep in mind these days are for me/cryptix, as nz is always a day in the future during these call times

**Comment by dominictarr** [comment]
yup sure, I'll be ready on mumble tuesday morning!

**Comment by cryptix** [comment]
> I am available Monday, Friday and Saturday at these times.

I guess you mean _Monday_ next week? All these three work for me but since mix is out I'd prefer Friday if that works for dom and mix.

**Comment by evbogue** [comment]
@cryptix I think dominic and I were talking about this week, but it was last week that we were talking about it.

I'll jump on mumble at 3pm CST and see if anyone is on today.

**Comment by cryptix** [comment]
Sorry but these short notices only work on rare occasions for me.

How about we move this thread to SSB?

**Comment by evbogue** [comment]
@cryptix I didn't end up making it either. Maybe a regular weekly call would be best, now that there are so many folks involved with development?

**Comment by mixmix** [comment]
keen to organise this on the butts, we can use gatherings perhaps to pin down the timezone
I'm happy to follow others lead
