### ISSUE TITLE
Uncaught TypeError: net.connect is not a function

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-client#53]
![image](https://user-images.githubusercontent.com/5776508/70197163-c8b39b80-16bf-11ea-8497-54503250e5dc.png)

multiserver error 

did a version change introduce this?

reproduce:
https://github.com/nichoth/eventual/tree/ee18e417f306f907bdd413ef442193b9e29c037f
`npm start`

**Comment by dominictarr** [comment]
I had a look at that code but it doesn't even depend on `ssb-client` so I don't see how it could have this error? is that the right link?

This error happens if it doesn't have a websocket address available, since the browser can't connect to net... but we should just fix it so that it at least has a helpful error message when you try to run this in the browser

**Comment by nichoth** [comment]
woops it looks like the link is

https://github.com/nichoth/eventual-gram/commit/ab9abe087d9cb10c7258882b6e89f50a8f205dff

`npm start` command to reproduce still

thanks @dominictarr
